### ISSUE TITLE
SQL-Schnittstelle

### ISSUE THREAD

**Issue by MariaMielke** [TimF91/Aufgabe_9.1#1]
Bezüglich des Metasuchportals wäre es interessant zu erfahren, ob eine SQL-Schnittstelle angeboten wird.

**Comment by TimF91** [comment]
Soweit mir bekannt bisher nicht - möglicherweise ist SQL dafür nicht das richtige Format. In der Regel werden Datenbanken (auch SQL-basierte) über das Web (SRU oder REST) abgefragt.
Das schließt aber nicht aus, dass verschiedene Datenbanken sql-basiert sind.
